import os

BINANCE_API_KEY = os.getenv("BINANCE_API_KEY", "")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET", "")

MAX_OPEN_POSITIONS = 3
MARGIN_PER_TRADE_USDT = 10
LEVERAGE = 5

PAPER_TRADING = True

BREAKEVEN_PCT = 1.0  
TRAILING_ACTIVATION_PCT = 1.5  

# 🛡️ YENİ EKLENEN FİLTRELER
COOLDOWN_MINUTES = 15 
VOLUME_MULTIPLIER = 1.5
